---
- name: Configure Linux Dev Environment
  hosts: all
  vars_files:
    - vars/global.yml
  handlers:
    - name: Update Desktop Database
      command: "/usr/bin/update-desktop-database"
      become: true
  pre_tasks:
    - name: "Set facts"
      set_fact:
        dpkg_arch: "{{ 'amd64' if (ansible_architecture == 'x86_64') else ansible_architecture }}"
    - name: "Meta: Create tempdir"
      tempfile:
        state: directory
      register: tempdir
    - name: "Meta: Create applications directory"
      file:
        path: /usr/local/share/applications
        state: directory
        owner: root
        group: root
        mode: "0755"
      become: true
  roles:
    # These roles need to run as the root user
    - role: packages
      become: true
    - role: aws
      become: true
    - role: utils
      become: true
    # These roles need to run as the user running the
    # playbook (either for security reasons or due to configuring
    # files in the home directory)
    - role: nvm
      become: false
    - role: python
      become: false
