---
- name: "Spring Tool Suite: Download"
  get_url:
    url: "{{ sts_download_url }}"
    dest: "{{ download_dir }}/spring.tar.gz"
    checksum: "sha1:{{ sts_sha1sum }}"
    timeout: 30
    force: true
- name: "Spring Tool Suite: Unarchive"
  unarchive:
    dest: "{{ opt_dir }}"
    src: "{{ download_dir }}/spring.tar.gz"
    owner: root
    group: root
    mode: "0755"
    remote_src: yes
- name: "Spring Tool Suite: Install .desktop file"
  template:
    src: templates/spring.desktop.j2
    dest: /usr/local/share/applications/spring.desktop
    mode: "0644"
  notify:
    - Update Desktop Database
