---
- name: "Packages: Upgrade all"
  ansible.builtin.apt:
    upgrade: full
    update_cache: true
- name: "Packages: Install requirements"
  ansible.builtin.apt:
    name: "{{ ubuntu_packages }}"
    state: latest
- name: "By default, use Java {{ default_java_version }}"
  community.general.alternatives:
    name: java
    path: "/usr/lib/jvm/java-{{ default_java_version }}-openjdk-{{ dpkg_arch }}/bin/java"
