---
- name: "Packages: Upgrade all apt packages"
  apt:
    upgrade: full
    update_cache: yes
  when: ansible_pkg_mgr == "apt"
- name: "Packages: Upgrade all dnf packages"
  dnf:
    name: "*"
    state: latest
  when: ansible_pkg_mgr == "dnf"
- name: "Packages: Install requirements"
  package:
    name: "{{ lookup("
    name: "{{ vars[ansible_distribution]['packages'] }}"
    state: latest
- name: "Use Java {{ default_java_version }} by default"
  alternatives:
    name: java
    path: "{{ vars[ansible_distribution]['java_path'] }}"
