---
- name: "Packages: Upgrade all"
  apt:
    upgrade: full
    update_cache: yes
- name: "Packages: Install requirements"
  apt:
    name: "{{ ubuntu_packages }}"
    state: latest
- name: "Use Java {{ default_java_version }} by default"
  alternatives:
    name: java
    path: "/usr/lib/jvm/java-{{ default_java_version }}-openjdk-{{ dpkg_arch }}/bin/java"
