---
- name: "pyenv: Install"
  git:
    repo: https://github.com/pyenv/pyenv.git
    dest: "{{ pyenv_dir }}"
- name: "pyenv: Install pyenv-virtualenv plugin"
  git:
    repo: https://github.com/pyenv/pyenv-virtualenv.git
    dest: "{{ pyenv_dir }}/plugins/pyenv-virtualenv"
- name: "pyenv: Install pyenv-update plugin"
  git:
    repo: https://github.com/pyenv/pyenv-update
    dest: "{{ pyenv_dir }}/plugins/pyenv-update"
- name: "pyenv: Install pyenv-doctor plugin"
  git:
    repo: https://github.com/pyenv/pyenv-doctor
    dest: "{{ pyenv_dir }}/plugins/pyenv-doctor"
- name: "pyenv: Place config in ~/.profile"
  blockinfile:
    path: ~/.profile
    block: |
      export PYENV_ROOT="$HOME/.pyenv"
      export PATH="$PYENV_ROOT/bin:$PATH"
      eval "$(pyenv init --path)"
      eval "$(pyenv init -)"
