---
- name: "Install"
  ansible.builtin.git:
    repo: https://github.com/pyenv/pyenv.git
    dest: "{{ pyenv_dir }}"
- name: "Install pyenv-virtualenv plugin"
  ansible.builtin.git:
    repo: https://github.com/pyenv/pyenv-virtualenv.git
    dest: "{{ pyenv_dir }}/plugins/pyenv-virtualenv"
- name: "Install pyenv-update plugin"
  ansible.builtin.git:
    repo: https://github.com/pyenv/pyenv-update
    dest: "{{ pyenv_dir }}/plugins/pyenv-update"
- name: "Install pyenv-doctor plugin"
  ansible.builtin.git:
    repo: https://github.com/pyenv/pyenv-doctor
    dest: "{{ pyenv_dir }}/plugins/pyenv-doctor"
- name: "Place config in ~/.bashrc"
  ansible.builtin.blockinfile:
    path: ~/.bashrc
    marker: "# {mark} ANSIBLE MANAGED PYENV CONFIG"
    block: |
      export PYENV_ROOT="$HOME/.pyenv"
      export PATH="$PYENV_ROOT/bin:$PATH"
      eval "$(pyenv init --path)"
      eval "$(pyenv init -)"
