#!/usr/bin/env bash

# Allows running actions on multiple services in WSL; converts calls from a
# systemctl-like syntax to a `service(8)` command invocations.

action="$1"
args=("$@")
args=("${args[@]:1}")

for service in "${args[@]}"; do
    service "$service" "$action"
done
